/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PoemsCollection {
  poems: {
    id: string;
    author: {
      id: string;
      name: string;
      [k: string]: unknown;
    };
    title: string;
    dedicatedTo?: string;
    text: string;
    footer?: string[];
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
