/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PoemsCollection {
  $schema?: string;
  poems: {
    id: string;
    author: {
      id: string;
      name: string;
    };
    title: string;
    epigraph?: string[];
    text: string;
    footer?: string[];
  }[];
}
